services:
  dev:
    working_dir: /app
    build:
        context: ../..
        dockerfile: Dockerfile
    container_name: dev
    dns: 8.8.8.8
    ports:
        - "4000:4000"
        - "80:4000"
    expose:
        - "4000"
        - "80"
    volumes:
      - $DIR:/app
